### ISSUE TITLE
Not able to signup for MahaDev

### ISSUE THREAD

**Issue by InderdeepBajwa** [MozillaIndia/homepage#79] opened 2016-07-23 12:15 UTC
While visiting the URL http://devs.mozillaindia.org/start/, I didn't found any link to the application form even after inspecting the elements, I didn't see any important link mentioned. Please let me know if it's an error or require brain to sign up.

**Comment by asdofindia** [comment] 2016-07-24 01:29
That's a trick.

**Comment by asdofindia** [comment] 2016-07-24 01:47
Actually, no such trick. This is a duplicate of #77. And neither belongs to this repository.

**Closed by asdofindia** 2016-07-24 01:47 UTC
