### ISSUE TITLE
No submitable form at Devs.MozillaIndia.org

### ISSUE THREAD

**Issue by InderdeepBajwa** [MozillaIndia/homepage#80] opened 2016-09-21 13:18 UTC
I would like to know if I could integrate Google forms in it, and would hide it using HTML to make it accessible only to people who actually know stuff about computers. Though jquery would not be easy but HTML will surely do a basic thing. One would be able to get instructions using Inspect Elements or by viewing source code of the webpage.
Would that be fine? And I am willing to refine applicant, mentor and also guide them for various ways they can contribute.
Would that be fine? Would like to hear suggestions.

**Comment by asdofindia** [comment] 2016-09-22 14:52
Duplicate of #77 and #79 and originally MozillaIndia/mozillaindia.github.io#6

**Closed by asdofindia** 2016-09-22 14:52 UTC
